# Generated by Django 5.0 on 2024-01-02 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_mst',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model', models.CharField(max_length=500)),
                ('ram', models.CharField(max_length=520)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_mst')),
            ],
        ),
    ]
